print('Olá, Mundo!')
print('Meu nome é Luís')
print('Estou aprendendo python na Nurap')
print('Achei a interface muito poluida para iniciantes')
print('Texto só para ocupar espaço')
print('Coisas para fazer')
print('Apertar ctrl+s')
print('Comer pipoca')
print('Ir à célula')
print('Treinar música')
print('Hoje eu aprendi a criar uma pasta e arquivo e escrever um texto modelo python')